#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/Data
src/String
src/Value
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCValueFoundation-import-private.h
src/reflect/_MulleObjCValueFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/Value/_MulleObjCConcreteValue-Private.h
src/Value/NSNumber-Private.h
src/Value/NSValue-Private.h
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCValueFoundation-import.h
src/reflect/_MulleObjCValueFoundation-include.h
)

set( PUBLIC_HEADERS
src/Data/_MulleObjCConcreteMutableData.h
src/Data/_MulleObjCDataSubclasses.h
src/Data/NSData+NSCoder.h
src/Data/NSData.h
src/Data/NSMutableData.h
src/MulleObjCLoader+MulleObjCValueFoundation.h
src/MulleObjCValueFoundation.h
src/String/_MulleObjCASCIIString.h
src/String/_MulleObjCCheatingASCIIString.h
src/String/_MulleObjCTaggedPointerChar5String.h
src/String/_MulleObjCTaggedPointerChar7String.h
src/String/_MulleObjCUTF16String.h
src/String/_MulleObjCUTF32String.h
src/String/NSConstantString.h
src/String/NSMutableString.h
src/String/NSObject+NSString.h
src/String/NSString+ClassCluster.h
src/String/NSString+NSCoder.h
src/String/NSString+NSData.h
src/String/NSStringObjCFunctions.h
src/String/NSString+Sprintf.h
src/String/NSString.h
src/String/mulle_sprintf_object.h
src/Value/_MulleObjCConcreteNumber.h
src/Value/_MulleObjCConcreteValue.h
src/Value/_MulleObjCTaggedPointerIntegerNumber.h
src/Value/NSDateFactory.h
src/Value/NSDate+NSCoder.h
src/Value/NSDate.h
src/Value/NSLock+NSDate.h
src/Value/NSNull.h
src/Value/NSNumber+NSCoder.h
src/Value/NSNumber+NSString.h
src/Value/NSNumber.h
src/Value/NSThread+NSDate.h
src/Value/NSValue+NSCoder.h
src/Value/NSValue.h
src/import.h
src/include.h
)

