#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/Data/_MulleObjCConcreteMutableData.m
src/Data/_MulleObjCDataSubclasses.m
src/Data/NSData+NSCoder.m
src/Data/NSData+Unicode.m
src/Data/NSData.m
src/Data/NSMutableData+Unicode.m
src/Data/NSMutableData.m
src/String/_MulleObjCASCIIString.m
src/String/_MulleObjCCheatingASCIIString.m
src/String/_MulleObjCTaggedPointerChar5String.m
src/String/_MulleObjCTaggedPointerChar7String.m
src/String/_MulleObjCUTF16String.m
src/String/_MulleObjCUTF32String.m
src/String/NSConstantString.m
src/String/NSData+NSString.m
src/String/NSMethodSignature+NSString.m
src/String/NSMutableData+NSString.m
src/String/NSMutableString+NSData.m
src/String/NSMutableString.m
src/String/NSObject+NSString.m
src/String/NSString+ClassCluster.m
src/String/NSString+NSCoder.m
src/String/NSString+NSData.m
src/String/NSStringObjCFunctions.m
src/String/NSString+Sprintf.m
src/String/NSString.m
src/String/mulle_sprintf_object.m
src/Value/_MulleObjCConcreteNumber+NSString.m
src/Value/_MulleObjCConcreteNumber.m
src/Value/_MulleObjCConcreteValue.m
src/Value/_MulleObjCTaggedPointerIntegerNumber.m
src/Value/NSDate+NSCoder.m
src/Value/NSDate.m
src/Value/NSLock+NSDate.m
src/Value/NSNull.m
src/Value/NSNumber+NSCoder.m
src/Value/NSNumber+NSString.m
src/Value/NSNumber.m
src/Value/NSThread+NSDate.m
src/Value/NSValue+NSCoder.m
src/Value/NSValue+NSString.m
src/Value/NSValue.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCValueFoundation.m
)
