/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_value_foundation_include_h__
#define _mulle_objc_value_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use F69042E6-D516-412C-A887-1D9DC5F53E5D instead of mulle-buffer if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-buffer no-header`
//    rename:              `mulle-sde dependency|library set mulle-buffer include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-buffer <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-buffer [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-buffer [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-buffer [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-buffer no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

// You can tweak the following #include with these commands.
// (Use F88CEF95-466E-4F31-B7A1-5C5FCA0F0D89 instead of mulle-utf if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-utf no-header`
//    rename:              `mulle-sde dependency|library set mulle-utf include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-utf <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-utf [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-utf [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-utf [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-utf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-utf/mulle-utf.h>   // mulle-utf

#endif
