      { @selector( NSConstantString), MULLE_OBJC_NO_CATEGORYID },      // 02cf74f7;NSConstantString;;
      { @selector( NSData), @selector( NSCoder) },      // 8fce7861;NSData;100c54ba;NSCoder
      { @selector( NSData), @selector( NSMutableCopying) },      // 8fce7861;NSData;4aa86031;NSMutableCopying
      { @selector( NSData), @selector( NSString) },      // 8fce7861;NSData;1994a171;NSString
      { @selector( NSData), @selector( _Unicode) },      // 8fce7861;NSData;ac921392;_Unicode
      { @selector( NSData), MULLE_OBJC_NO_CATEGORYID },      // 8fce7861;NSData;;
      { @selector( NSMethodSignature), @selector( NSString) },      // 523989f9;NSMethodSignature;1994a171;NSString
      { @selector( NSMutableData), @selector( NSCoder) },      // 5d7fdc81;NSMutableData;100c54ba;NSCoder
      { @selector( NSMutableData), @selector( NSString) },      // 5d7fdc81;NSMutableData;1994a171;NSString
      { @selector( NSMutableData), @selector( Unicode) },      // 5d7fdc81;NSMutableData;94ece403;Unicode
      { @selector( NSMutableData), MULLE_OBJC_NO_CATEGORYID },      // 5d7fdc81;NSMutableData;;
      { @selector( NSMutableString), @selector( NSData) },      // 63662493;NSMutableString;8fce7861;NSData
      { @selector( NSMutableString), MULLE_OBJC_NO_CATEGORYID },      // 63662493;NSMutableString;;
      { @selector( NSNumber), @selector( NSCoder) },      // 8ba34f39;NSNumber;100c54ba;NSCoder
      { @selector( NSNumber), @selector( NSString) },      // 8ba34f39;NSNumber;1994a171;NSString
      { @selector( NSNumber), MULLE_OBJC_NO_CATEGORYID },      // 8ba34f39;NSNumber;;
      { @selector( NSObject), @selector( NSString) },      // b3a66256;NSObject;1994a171;NSString
      { @selector( NSObject), @selector( _NSData) },      // b3a66256;NSObject;7f24339e;_NSData
      { @selector( NSObject), @selector( _NSMutableData) },      // b3a66256;NSObject;1a3fbdd6;_NSMutableData
      { @selector( NSObject), @selector( _NSMutableString) },      // b3a66256;NSObject;7bd64f0d;_NSMutableString
      { @selector( NSObject), @selector( _NSNumber) },      // b3a66256;NSObject;9343014d;_NSNumber
      { @selector( NSObject), @selector( _NSString) },      // b3a66256;NSObject;37e49041;_NSString
      { @selector( NSObject), @selector( _NSValue) },      // b3a66256;NSObject;8fc3f568;_NSValue
      { @selector( NSString), @selector( ClassCluster) },      // 1994a171;NSString;d38b16ff;ClassCluster
      { @selector( NSString), @selector( Enumerator) },      // 1994a171;NSString;bd761fff;Enumerator
      { @selector( NSString), @selector( NSCoder) },      // 1994a171;NSString;100c54ba;NSCoder
      { @selector( NSString), @selector( NSData) },      // 1994a171;NSString;8fce7861;NSData
      { @selector( NSString), @selector( NSDataPrivate) },      // 1994a171;NSString;542e5a5f;NSDataPrivate
      { @selector( NSString), @selector( NSMutableString) },      // 1994a171;NSString;63662493;NSMutableString
      { @selector( NSString), @selector( Sprintf) },      // 1994a171;NSString;8d371e94;Sprintf
      { @selector( NSString), MULLE_OBJC_NO_CATEGORYID },      // 1994a171;NSString;;
      { @selector( NSThread), @selector( NSString) },      // c81b9c22;NSThread;1994a171;NSString
      { @selector( NSValue), @selector( NSCoder) },      // 96deaa7d;NSValue;100c54ba;NSCoder
      { @selector( NSValue), @selector( NSString) },      // 96deaa7d;NSValue;1994a171;NSString
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // 96deaa7d;NSValue;;
      { @selector( _MulleObjCASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b82142dd;_MulleObjCASCIIString;;
      { @selector( _MulleObjCAllocatorASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b8b17987;_MulleObjCAllocatorASCIIString;;
      { @selector( _MulleObjCAllocatorData), MULLE_OBJC_NO_CATEGORYID },      // 888d9e62;_MulleObjCAllocatorData;;
      { @selector( _MulleObjCAllocatorUTF16String), MULLE_OBJC_NO_CATEGORYID },      // fadd0998;_MulleObjCAllocatorUTF16String;;
      { @selector( _MulleObjCAllocatorUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 22d56278;_MulleObjCAllocatorUTF32String;;
      { @selector( _MulleObjCAllocatorZeroTerminatedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a747ff17;_MulleObjCAllocatorZeroTerminatedASCIIString;;
      { @selector( _MulleObjCBoolNumber), @selector( NSString) },      // 263c5445;_MulleObjCBoolNumber;1994a171;NSString
      { @selector( _MulleObjCBoolNumber), MULLE_OBJC_NO_CATEGORYID },      // 263c5445;_MulleObjCBoolNumber;;
      { @selector( _MulleObjCCheatingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // c16079ee;_MulleObjCCheatingASCIIString;;
      { @selector( _MulleObjCConcreteData), MULLE_OBJC_NO_CATEGORYID },      // 9971ffa3;_MulleObjCConcreteData;;
      { @selector( _MulleObjCConcreteMutableData), MULLE_OBJC_NO_CATEGORYID },      // 55d549c0;_MulleObjCConcreteMutableData;;
      { @selector( _MulleObjCConcreteValue), @selector( NSCoder) },      // 7aa5a738;_MulleObjCConcreteValue;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // 7aa5a738;_MulleObjCConcreteValue;;
      { @selector( _MulleObjCDoubleNumber), @selector( NSString) },      // ae25b758;_MulleObjCDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // ae25b758;_MulleObjCDoubleNumber;;
      { @selector( _MulleObjCEightBytesData), MULLE_OBJC_NO_CATEGORYID },      // 7ac60bf2;_MulleObjCEightBytesData;;
      { @selector( _MulleObjCFloatNumber), @selector( NSString) },      // 0efef7c5;_MulleObjCFloatNumber;1994a171;NSString
      { @selector( _MulleObjCFloatNumber), MULLE_OBJC_NO_CATEGORYID },      // 0efef7c5;_MulleObjCFloatNumber;;
      { @selector( _MulleObjCGenericASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 2c4a2683;_MulleObjCGenericASCIIString;;
      { @selector( _MulleObjCGenericUTF16String), MULLE_OBJC_NO_CATEGORYID },      // ceb45c9e;_MulleObjCGenericUTF16String;;
      { @selector( _MulleObjCGenericUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 57fe0d78;_MulleObjCGenericUTF32String;;
      { @selector( _MulleObjCInt32Number), @selector( NSString) },      // d69971a0;_MulleObjCInt32Number;1994a171;NSString
      { @selector( _MulleObjCInt32Number), MULLE_OBJC_NO_CATEGORYID },      // d69971a0;_MulleObjCInt32Number;;
      { @selector( _MulleObjCInt64Number), @selector( NSString) },      // 8b4d5e19;_MulleObjCInt64Number;1994a171;NSString
      { @selector( _MulleObjCInt64Number), MULLE_OBJC_NO_CATEGORYID },      // 8b4d5e19;_MulleObjCInt64Number;;
      { @selector( _MulleObjCLongDoubleNumber), @selector( NSString) },      // 4ec38072;_MulleObjCLongDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCLongDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 4ec38072;_MulleObjCLongDoubleNumber;;
      { @selector( _MulleObjCMediumData), MULLE_OBJC_NO_CATEGORYID },      // bcd94429;_MulleObjCMediumData;;
      { @selector( _MulleObjCReferencingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b6861455;_MulleObjCReferencingASCIIString;;
      { @selector( _MulleObjCSharedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a4a89e62;_MulleObjCSharedASCIIString;;
      { @selector( _MulleObjCSharedData), MULLE_OBJC_NO_CATEGORYID },      // 71db1e02;_MulleObjCSharedData;;
      { @selector( _MulleObjCSharedUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 06c03572;_MulleObjCSharedUTF16String;;
      { @selector( _MulleObjCSharedUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 6762de13;_MulleObjCSharedUTF32String;;
      { @selector( _MulleObjCSixteenBytesData), MULLE_OBJC_NO_CATEGORYID },      // 4b47402e;_MulleObjCSixteenBytesData;;
      { @selector( _MulleObjCTaggedPointerChar5String), MULLE_OBJC_NO_CATEGORYID },      // 2a6d1009;_MulleObjCTaggedPointerChar5String;;
      { @selector( _MulleObjCTaggedPointerChar7String), MULLE_OBJC_NO_CATEGORYID },      // d68ecb24;_MulleObjCTaggedPointerChar7String;;
      { @selector( _MulleObjCTaggedPointerDoubleNumber), @selector( NSCoder) },      // 332cd0a3;_MulleObjCTaggedPointerDoubleNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 332cd0a3;_MulleObjCTaggedPointerDoubleNumber;;
      { @selector( _MulleObjCTaggedPointerFloatNumber), @selector( NSCoder) },      // 4ec9e1de;_MulleObjCTaggedPointerFloatNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerFloatNumber), MULLE_OBJC_NO_CATEGORYID },      // 4ec9e1de;_MulleObjCTaggedPointerFloatNumber;;
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSCoder) },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSString) },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;1994a171;NSString
      { @selector( _MulleObjCTaggedPointerIntegerNumber), MULLE_OBJC_NO_CATEGORYID },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;;
      { @selector( _MulleObjCTinyASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a20ee3f6;_MulleObjCTinyASCIIString;;
      { @selector( _MulleObjCTinyData), MULLE_OBJC_NO_CATEGORYID },      // ed2fbb7a;_MulleObjCTinyData;;
      { @selector( _MulleObjCUInt32Number), @selector( NSString) },      // 92030c9c;_MulleObjCUInt32Number;1994a171;NSString
      { @selector( _MulleObjCUInt32Number), MULLE_OBJC_NO_CATEGORYID },      // 92030c9c;_MulleObjCUInt32Number;;
      { @selector( _MulleObjCUInt64Number), @selector( NSString) },      // c62e3ae1;_MulleObjCUInt64Number;1994a171;NSString
      { @selector( _MulleObjCUInt64Number), MULLE_OBJC_NO_CATEGORYID },      // c62e3ae1;_MulleObjCUInt64Number;;
      { @selector( _MulleObjCUTF16String), MULLE_OBJC_NO_CATEGORYID },      // d817650f;_MulleObjCUTF16String;;
      { @selector( _MulleObjCUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 318d8f60;_MulleObjCUTF32String;;
      { @selector( _MulleObjCZeroBytesData), MULLE_OBJC_NO_CATEGORYID },      // e3b0c32a;_MulleObjCZeroBytesData;;
